name: Middleman

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/cache@v1
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gems-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

        #   - uses: actions/setup-ruby@v1
        #   with:
        #     ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
        # - run: ruby hello.rb

    #   - name: Build & Deploy to GitHub Pages
    #     with:
    #       REMOTE_BRANCH: gh-pages
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     uses: yurikoval/middleman-gh-pages-action@master


    #         runs-on: ubuntu-16.04
    # strategy:
    #   matrix:
    #     ruby: [ '2.5', '2.6' ]
    # name: Ruby ${{ matrix.ruby }} sample
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-ruby@v1
    #     with:
    #       ruby-version: ${{ matrix.ruby }}
    #   - run: ruby hello.rb